# Project identification
sonar.organization=smikey1org
sonar.projectKey=shopivo-order-service
sonar.projectName=shopivo-order-service
sonar.projectVersion=1.0

# Path to source code
sonar.sources=src

# Source exclusions
sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**,**/.venv/**,**/venv/**

# Path to tests
sonar.tests=tests

# Test exclusions
sonar.test.exclusions=**/__pycache__/**,**/.pytest_cache/**

# Python version
sonar.python.version=3.14

# Coverage report
sonar.python.coverage.reportPaths=coverage.xml

# Source encoding
sonar.sourceEncoding=UTF-8
